### ISSUE TITLE
It didnt worked for me.

### ISSUE THREAD

**Issue by BartekkH** [AmitBokoDev/9gag-post-filter#1]
Please take a look, if you need some logs, let me know:)

![image](https://user-images.githubusercontent.com/27912350/217916542-d1831f49-5a74-4a48-a3d0-4f02ced2e9be.png)

**Comment by AmitBokoDev** [comment]
@BartekkH you didn't set a day limit, the gray "300" is an example placeholder, which I've changed in an update that's waiting for a review. Write an actual number and refresh.

**Comment by BartekkH** [comment]
@AmitBokoDev  I thought its "preset" now i get it! :)
