### ISSUE TITLE
tags / titles filter 

### ISSUE THREAD

**Issue by xristoschristos** [AmitBokoDev/9gag-post-filter#3]
tags,titles filter doesnt work , multiple keys or single same result (also ive already given it perm for https )

**Comment by xristoschristos** [comment]
![Uploading asdasd.png…]()

**Comment by AmitBokoDev** [comment]
@xristoschristos 
I know of this issue, I am currently working on an update that will fix that and also add some new features. 
I am currently in the process of moving so it will take some time.

**Comment by AmitBokoDev** [comment]
@xristoschristos fixed in the new version, wait a day or so for the update
