### ISSUE TITLE
Bandwidth savings?!

### ISSUE THREAD

**Issue by r3a1d3a1** [AmitBokoDev/9gag-post-filter#4]
Hello. I don't suppose this actually saves any bandwidth. Does it?!
It may not matter much for pics, but for videos, probably only the first few seconds are loaded in the background?

https://stackoverflow.com/questions/4099637/does-displaynone-keep-elements-from-loading

**Comment by AmitBokoDev** [comment]
It's a possibility, but the code also makes many extra http requests to get the data on the users themselves, so I'm not sure. 
I might test it in the future.
